version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: naitais
  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"